// All personal content lives here.
export const content = {
  name: "Jahangir Alam Tamal",
  headline: "Software Engineer",
  subtext: "I build robust, scalable software and digital products end to end.",
  email: "hello@tamal.dev",
  resumeUrl: "/resume.pdf",
  socials: [
    { label: "Claude", url: "https://claude.ai" },
    { label: "YouTube", url: "https://youtube.com" },
    { label: "ChatGPT", url: "https://chatgpt.com" },
  ],
  experience: [
    {
      company: "Donoro",
      icon: "code",
      url: "https://donoroapp.com/",
      logo: "/badges/donoro.png",
      logoInvert: false,
      location: "Dhaka, Bangladesh",
      locationNote: "(Remote / Hybrid)",
      role: "Software Engineer",
      type: "Full-time",
      start: "01.2025",
      end: null, // present
      duration: "Present",
      highlights: [
        "Architect and engineer the core platform for [[Donoro|https://donoroapp.com/]], Bangladesh's real-time emergency blood donation and donor matching network.",
        "Develop high-performance REST APIs, real-time alert dispatch pipelines, and emergency response workflows.",
        "Build responsive, accessible user interfaces and state-driven mobile/web application features.",
        "Scale distributed services and streamline verification mechanisms for donors and requesters nationwide.",
      ],
      tags: ["Next.js", "TypeScript", "React", "Node.js", "Tailwind CSS", "Real-time", "System Design"],
    },
    {
      company: "Orbix Studio",
      icon: "code",
      url: "https://www.orbix.studio/",
      logo: "/badges/orbix.png",
      logoInvert: false,
      location: "Dhaka, Bangladesh",
      locationNote: "(Hybrid)",
      role: "Frontend Engineer",
      type: "Full Time",
      start: "Jan 2024",
      end: "Dec 2024",
      duration: "1 yr",
      highlights: [
        "Engineered interactive web applications with optimal performance.",
        "Collaborated with product teams to build accessible, fluid interfaces.",
        "Integrated complex REST & GraphQL APIs.",
      ],
      tags: ["TypeScript", "Next.js", "Tailwind CSS", "REST APIs"],
    },
    {
      company: "ScreensDesigns",
      icon: "code",
      url: "https://screensdesign.com",
      logo: "/badges/screens.png",
      logoInvert: false,
      location: "Tallinn, Estonia",
      locationNote: "(Remote)",
      role: "Software Engineer",
      type: "Contract",
      start: "Feb 2023",
      end: "Dec 2023",
      duration: "11m",
      highlights: [
        "Built and maintained responsive web applications.",
        "Refactored legacy codebases to modern TypeScript & React standards.",
      ],
      tags: ["React", "JavaScript", "HTML/CSS", "Full Stack"],
    },
  ],
  projects: [
    {
      name: "Donoro",
      description: "All-in-one blood donation & emergency matching platform\n— Full Stack Engineering & Architecture",
      image: "/projects/donoro.png",
      url: "https://donoroapp.com/",
      note: "Live",
    },
    {
      name: "Vivetica",
      description: "Scalable enterprise web application\n— Frontend & Architecture",
      image: "/projects/vivetica.png",
      url: "https://vivetica.vercel.app/",
      note: null,
    },
    {
      name: "VisualPillar",
      description: "Full-cycle digital solutions platform\n— Full Stack Development",
      image: "/projects/placeholder.png",
      url: "#",
      note: "In Development",
    },
  ],
  skills: [
    {
      index: "01",
      name: "Languages",
      items: [
        { name: "JavaScript", icon: "javascript" },
        { name: "TypeScript", icon: "typescript" },
        { name: "HTML", icon: "html" },
        { name: "CSS", icon: "css" },
      ],
    },
    {
      index: "02",
      name: "Frontend",
      items: [
        { name: "React", icon: "react" },
        { name: "Next.js", icon: "nextjs" },
        { name: "Tailwind CSS", icon: "tailwind" },
        { name: "shadcn/ui", icon: "shadcn" },
        { name: "Radix UI", icon: "radix" },
        { name: "Motion", icon: "motion" },
      ],
    },
    {
      index: "03",
      name: "Tools & DevOps",
      items: [
        { name: "Git", icon: "git" },
        { name: "GitHub", icon: "github" },
        { name: "VS Code", icon: "vscode" },
        { name: "Docker", icon: "docker" },
        { name: "Vercel", icon: "vercel" },
        { name: "Cursor", icon: "cursor" },
      ],
    },
    {
      index: "04",
      name: "Design & AI",
      items: [
        { name: "Figma", icon: "figma" },
        { name: "Claude", icon: "claude" },
        { name: "ChatGPT", icon: "chatgpt" },
        { name: "Gemini", icon: "gemini" },
      ],
    },
  ],
  archive: [
    {
      year: "2026",
      name: "TRH CGI",
      description: "Web application for a Paris creative studio.",
      url: "https://github.com/fiftee15n",
    },
    {
      year: "2026",
      name: "Pintop",
      description: "Pin any window always-on-top utility.",
      url: "https://github.com/fiftee15n",
    },
    {
      year: "2025",
      name: "Vucko",
      description: "High performance web application with motion.",
      url: "https://github.com/fiftee15n",
    },
  ],
} as const;
