// All personal content lives here.
export const content = {
  name: "Jahangir Alam Tamal",
  headline: "Software Engineer",
  subtext: "I build robust, scalable software and digital products end to end.",
  email: "hello@tamal.dev",
  resumeUrl: "/resume.pdf",
  socials: [
    { label: "Claude", url: "https://claude.ai" },
    { label: "YouTube", url: "https://youtube.com" },
    { label: "ChatGPT", url: "https://chatgpt.com" },
  ],
  experience: [
    {
      company: "Donoro",
      icon: "code",
      url: "https://donoroapp.com/",
      logo: "/badges/donoro.png",
      logoInvert: false,
      location: "Dhaka, Bangladesh",
      locationNote: "(Remote / Hybrid)",
      role: "Software Engineer",
      type: "Full-time",
      start: "01.2025",
      end: null, // present
      duration: "Present",
      highlights: [
        "Architect and engineer the core platform for [[Donoro|https://donoroapp.com/]], Bangladesh's real-time emergency blood donation and donor matching network.",
        "Develop high-performance REST APIs, real-time alert dispatch pipelines, and emergency response workflows.",
        "Build responsive, accessible user interfaces and state-driven mobile/web application features.",
        "Scale distributed services and streamline verification mechanisms for donors and requesters nationwide.",
      ],
      tags: ["Next.js", "TypeScript", "React", "Node.js", "Tailwind CSS", "Real-time", "System Design"],
    },
    {
      company: "Orbix Studio",
      icon: "code",
      url: "https://www.orbix.studio/",
      logo: "/badges/orbix.png",
      logoInvert: false,
      location: "Dhaka, Bangladesh",
      locationNote: "(Hybrid)",
      role: "Frontend Engineer",
      type: "Full Time",
      start: "Jan 2024",
      end: "Dec 2024",
      duration: "1 yr",
      highlights: [
        "Engineered interactive web applications with optimal performance.",
        "Collaborated with product teams to build accessible, fluid interfaces.",
        "Integrated complex REST & GraphQL APIs.",
      ],
      tags: ["TypeScript", "Next.js", "Tailwind CSS", "REST APIs"],
    },
    {
      company: "ScreensDesigns",
      icon: "code",
      url: "https://screensdesign.com",
      logo: "/badges/screens.png",
      logoInvert: false,
      location: "Tallinn, Estonia",
      locationNote: "(Remote)",
      role: "Software Engineer",
      type: "Contract",
      start: "Feb 2023",
      end: "Dec 2023",
      duration: "11m",
      highlights: [
        "Built and maintained responsive web applications.",
        "Refactored legacy codebases to modern TypeScript & React standards.",
      ],
      tags: ["React", "JavaScript", "HTML/CSS", "Full Stack"],
    },
  ],
  projects: [
    {
      name: "Donoro",
      description: "All-in-one blood donation & emergency matching platform\n— Product Lead & Architecture",
      image: "/projects/donoro.png",
      url: "https://donoroapp.com/",
      note: "Live",
    },
    {
      name: "Evalua",
      description: "Scalable Edtech Platform for promising Students in Bangladesh\n— Full Stack Engineer & Architecture",
      image: "/projects/evalua.png",
      url: "https://evalua.app/",
      note: null,
    },
  ],
  skills: [
    {
      index: "01",
      name: "Languages",
      items: [
        { name: "JavaScript", icon: "javascript" },
        { name: "TypeScript", icon: "typescript" },
        { name: "HTML", icon: "html" },
        { name: "CSS", icon: "css" },
      ],
    },
    {
      index: "02",
      name: "Frontend",
      items: [
        { name: "React", icon: "react" },
        { name: "Next.js", icon: "nextjs" },
        { name: "Tailwind CSS", icon: "tailwind" },
        { name: "shadcn/ui", icon: "shadcn" },
        { name: "Radix UI", icon: "radix" },
        { name: "Motion", icon: "motion" },
      ],
    },
    {
      index: "03",
      name: "Tools & DevOps",
      items: [
        { name: "Git", icon: "git" },
        { name: "GitHub", icon: "github" },
        { name: "VS Code", icon: "vscode" },
        { name: "Docker", icon: "docker" },
        { name: "Vercel", icon: "vercel" },
        { name: "Cursor", icon: "cursor" },
      ],
    },
    {
      index: "04",
      name: "Design & AI",
      items: [
        { name: "Figma", icon: "figma" },
        { name: "Claude", icon: "claude" },
        { name: "ChatGPT", icon: "chatgpt" },
        { name: "Gemini", icon: "gemini" },
      ],
    },
  ],
  archive: [
    {
      year: "2024",
      name: "Petsrology",
      description: "Pet care, adoption & management platform.",
      url: "https://github.com/fiftee15n/Petsrology_webapp",
    },
    {
      year: "2024",
      name: "Bazar-Saadai",
      description: "Online grocery & marketplace platform.",
      url: "https://github.com/fiftee15n/bazar_sadaai",
    },
  ],
  education: [
    {
      degree: "B.Sc in Computer Science & Engineering",
      institution: "Daffodil International University",
      grade: "CGPA: 3.30 out of 4.00",
      image: "/education/diu.jpg",
      highlights: [
        "Top 50 among 2000 students in Takeoff Programming Contest",
        "Unlock the Algorithm Competition",
        "Inter University Contest - Data Visionary",
        "IDAA 2025 Conference Participant",
      ],
    },
    {
      degree: "Higher Secondary Certificate (HSC)",
      institution: "BAF Shaheen College Kurmitola",
      grade: "Golden GPA: 5.00 | Science Group",
      image: "/education/bafsk.jpg",
      highlights: [
        "Active member of Atomic BAFSK Science Club",
        "Photography Club Member",
        "Excellent academic performance with distinction",
        "Strong foundation in Science and Mathematics",
      ],
    },
    {
      degree: "Secondary School Certificate (SSC)",
      institution: "B.M. Union School & College",
      grade: "Golden GPA: 5.00 | Science Group",
      image: "/education/bmunion.png",
      highlights: [
        "Scouting Member - Leadership and teamwork skills",
        "Science Fair Participant",
        "Top 3 in Science Carnival",
        "Demonstrated early excellence in academics",
      ],
    },
  ],
  certifications: [
    {
      title: "IDAA 2025 - Research Paper Publication",
      description: "Self-Distilled Vision Transformer (SD-ViT) to Classify Brain Tumors using MRI images",
      date: "Paper published on June 2026",
      image: "/certifications/idaa-2025.jpg",
    },
    {
      title: "DevFest - AI Innovation Workshop",
      description: "Real-World Applications with Google Gemini & Vertex AI",
      date: "Completed: 2024",
      image: "/certifications/devfest.png",
    },
    {
      title: "Data Visionary Competition",
      description: "Inter University Contest",
      date: "Completed: 2025",
      image: "/certifications/data-visionary.jpg",
    },
    {
      title: "RURS 1st International Student Conference",
      description: "Research Fair 2024 - University of Rajshahi",
      date: "Completed: 2024",
      image: "/certifications/rurs-conference.jpg",
    },
    {
      title: "Unlock the Algorithm Competition",
      description: "Daffodil International University",
      date: "Completed: 2023",
      image: "/certifications/unlock-algorithm.jpg",
    },
    {
      title: "Takeoff Programming Contest 2022",
      description: "Top 50 among 2000 participants",
      date: "Completed: 2022",
      image: "/certifications/takeoff-2022.jpg",
    },
  ],
} as const;
